default_context:
  author_name: "Roberto Vera Alvarez"
  user_email: "veraalva@ncbi.nlm.nih.gov"
  project_name: "pm4ngs-chipseq"
  dataset_name: "PRJNA481982"
  is_data_in_SRA: "y"
  sequencing_technology: "paired-end"
  create_demo: "y"
  number_spots: "1000000"
  organism: "mouse"
  genome_name: "mm9"
  genome_dir: "mm9"
  aligner_index_dir: "{{ cookiecutter.genome_dir}}/BWA/"
  genome_fasta: "{{ cookiecutter.genome_dir}}/genome.fa"
  genome_gtf: "{{ cookiecutter.genome_dir}}/genes.gtf"
  genome_mappable_size: "mm"
  fdr: "0.05"
  use_docker: "y"
  cwl_workflow_repo: "https://github.com/ncbi/cwl-ngs-workflows-cbb"
  max_number_threads: "32"
