name: chipseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bamtools=2.5.1
  - bcftools=1.10.2
  - bedtools=2.29.2
  - bioconductor-diffbind=2.16.0
  - bwa=0.7.17
  - fastqc=0.11.9
  - idr=2.0.4.2
  - igvtools=2.5.3
  - homer=4.11
  - macs2=2.2.7.1
  - phantompeakqualtools=1.2.2
  - samtools=1.10
  - sra-tools=2.10.8
  - trimmomatic=0.39
  - ucsc-gtftogenepred=377
  - ucsc-genepredtobed=377
